# Copyright The Platform Mesh Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if and .gatewayApi.enabled (eq .deploymentTechnology "argocd") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .gatewayApi.name }}
  namespace: {{ .helmReleaseNamespace }}
  labels:
    core.platform-mesh.io/operator-created: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .gatewayApi.syncWave | default 0 }}"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-mesh-runtime
  {{- if .gatewayApi.ignoreDifferences }}
  ignoreDifferences:
{{ toYaml .gatewayApi.ignoreDifferences | nindent 4 }}
  {{- end }}
  source:
    chart: {{ .gatewayApi.name }}
    {{- if and .gatewayApi.repoURL (ne .gatewayApi.repoURL "") }}
    repoURL: {{ .gatewayApi.repoURL }}
    {{- else }}
    repoURL: PLACEHOLDER_TO_BE_SET_BY_RESOURCE_SUBROUTINE
    {{- end }}
    {{- if and .gatewayApi.targetRevision (ne .gatewayApi.targetRevision "") }}
    targetRevision: {{ .gatewayApi.targetRevision }}
    {{- else }}
    targetRevision: PLACEHOLDER_TO_BE_SET_BY_RESOURCE_SUBROUTINE
    {{- end }}
  destination:
    server: {{ .destinationServer | default "https://kubernetes.default.svc" }}
    namespace: {{ .releaseNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    {{- if .gatewayApi.syncOptions }}
    syncOptions:
{{ toYaml .gatewayApi.syncOptions | nindent 4 }}
    {{- else }}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    {{- if .gatewayApi.ignoreDifferences }}
    - RespectIgnoreDifferences=true
    {{- end }}
    {{- if and .gatewayApi.kustomization .gatewayApi.kustomization.install .gatewayApi.kustomization.install.crds (eq .gatewayApi.kustomization.install.crds "Skip") }}
    - SkipDryRunOnMissingResource=true
    {{- end }}
    {{- end }}
{{- end }}

