apiVersion: backup.platform-mesh.io/v1alpha1
kind: PlatformBackup
metadata:
  name: platformbackup-velero-sample
spec:
  storage:
    s3:
      endpoint: http://minio.platform-mesh-system.svc.cluster.local:9000
      bucket: velero-backups
      region: us-east-1
      credentialsRef:
        name: velero-backup-s3
  components:
    etcd:
      enabled: true
    cnpg:
      enabled: true
    velero:
      enabled: true
