# The default kubeconfig for broker points to kcp, this is the
# kubeconfig for the "compute" cluster to deploy migrations in.
# In production this would point to a runtime or even dedicated cluster.
# Or better - a dedicated workspace to deploy resources for other
# operators to pick up.
apiVersion: v1
kind: ConfigMap
metadata:
  name: compute-kubeconfig
  namespace: resource-broker-system
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: in-cluster
        cluster:
          server: https://kubernetes.default.svc
          certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    users:
      - name: in-cluster
        user:
          tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
      - name: in-cluster
        context:
          cluster: in-cluster
          user: in-cluster
    current-context: in-cluster
