apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../config/broker/default
- rbac.yaml
- compute-kubeconfig.yaml

images:
- name: ghcr.io/platform-mesh/resource-broker
  newName: localhost/resource-broker
  newTag: dev

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: resource-broker
    spec:
      template:
        spec:
          containers:
            - name: resource-broker
              args:
                - -kubeconfig=/kubeconfig/kubeconfig
                - -kcp-kubeconfig=/kubeconfig/kubeconfig
                - -compute-kubeconfig=/compute-kubeconfig/kubeconfig
                - -acceptapi=acceptapis
                - -requeue-interval=1s
              volumeMounts:
                - name: compute-kubeconfig
                  mountPath: /compute-kubeconfig
                  readOnly: true
          volumes:
            - name: compute-kubeconfig
              configMap:
                name: compute-kubeconfig
