/*
Copyright The Platform Mesh Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// NewSubResourceWriter creates a new instance of SubResourceWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubResourceWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubResourceWriter {
	mock := &SubResourceWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SubResourceWriter is an autogenerated mock type for the SubResourceWriter type
type SubResourceWriter struct {
	mock.Mock
}

type SubResourceWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *SubResourceWriter) EXPECT() *SubResourceWriter_Expecter {
	return &SubResourceWriter_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type SubResourceWriter
func (_mock *SubResourceWriter) Apply(ctx context.Context, obj runtime.ApplyConfiguration, opts ...client.SubResourceApplyOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, obj, opts)
	} else {
		tmpRet = _mock.Called(ctx, obj)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, runtime.ApplyConfiguration, ...client.SubResourceApplyOption) error); ok {
		r0 = returnFunc(ctx, obj, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubResourceWriter_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type SubResourceWriter_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - obj runtime.ApplyConfiguration
//   - opts ...client.SubResourceApplyOption
func (_e *SubResourceWriter_Expecter) Apply(ctx interface{}, obj interface{}, opts ...interface{}) *SubResourceWriter_Apply_Call {
	return &SubResourceWriter_Apply_Call{Call: _e.mock.On("Apply",
		append([]interface{}{ctx, obj}, opts...)...)}
}

func (_c *SubResourceWriter_Apply_Call) Run(run func(ctx context.Context, obj runtime.ApplyConfiguration, opts ...client.SubResourceApplyOption)) *SubResourceWriter_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 runtime.ApplyConfiguration
		if args[1] != nil {
			arg1 = args[1].(runtime.ApplyConfiguration)
		}
		var arg2 []client.SubResourceApplyOption
		var variadicArgs []client.SubResourceApplyOption
		if len(args) > 2 {
			variadicArgs = args[2].([]client.SubResourceApplyOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *SubResourceWriter_Apply_Call) Return(err error) *SubResourceWriter_Apply_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubResourceWriter_Apply_Call) RunAndReturn(run func(ctx context.Context, obj runtime.ApplyConfiguration, opts ...client.SubResourceApplyOption) error) *SubResourceWriter_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type SubResourceWriter
func (_mock *SubResourceWriter) Create(ctx context.Context, obj client.Object, subResource client.Object, opts ...client.SubResourceCreateOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, obj, subResource, opts)
	} else {
		tmpRet = _mock.Called(ctx, obj, subResource)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.Object, client.Object, ...client.SubResourceCreateOption) error); ok {
		r0 = returnFunc(ctx, obj, subResource, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubResourceWriter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SubResourceWriter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - obj client.Object
//   - subResource client.Object
//   - opts ...client.SubResourceCreateOption
func (_e *SubResourceWriter_Expecter) Create(ctx interface{}, obj interface{}, subResource interface{}, opts ...interface{}) *SubResourceWriter_Create_Call {
	return &SubResourceWriter_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{ctx, obj, subResource}, opts...)...)}
}

func (_c *SubResourceWriter_Create_Call) Run(run func(ctx context.Context, obj client.Object, subResource client.Object, opts ...client.SubResourceCreateOption)) *SubResourceWriter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.Object
		if args[1] != nil {
			arg1 = args[1].(client.Object)
		}
		var arg2 client.Object
		if args[2] != nil {
			arg2 = args[2].(client.Object)
		}
		var arg3 []client.SubResourceCreateOption
		var variadicArgs []client.SubResourceCreateOption
		if len(args) > 3 {
			variadicArgs = args[3].([]client.SubResourceCreateOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *SubResourceWriter_Create_Call) Return(err error) *SubResourceWriter_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubResourceWriter_Create_Call) RunAndReturn(run func(ctx context.Context, obj client.Object, subResource client.Object, opts ...client.SubResourceCreateOption) error) *SubResourceWriter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function for the type SubResourceWriter
func (_mock *SubResourceWriter) Patch(ctx context.Context, obj client.Object, patch client.Patch, opts ...client.SubResourcePatchOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, obj, patch, opts)
	} else {
		tmpRet = _mock.Called(ctx, obj, patch)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.Object, client.Patch, ...client.SubResourcePatchOption) error); ok {
		r0 = returnFunc(ctx, obj, patch, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubResourceWriter_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type SubResourceWriter_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - obj client.Object
//   - patch client.Patch
//   - opts ...client.SubResourcePatchOption
func (_e *SubResourceWriter_Expecter) Patch(ctx interface{}, obj interface{}, patch interface{}, opts ...interface{}) *SubResourceWriter_Patch_Call {
	return &SubResourceWriter_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, obj, patch}, opts...)...)}
}

func (_c *SubResourceWriter_Patch_Call) Run(run func(ctx context.Context, obj client.Object, patch client.Patch, opts ...client.SubResourcePatchOption)) *SubResourceWriter_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.Object
		if args[1] != nil {
			arg1 = args[1].(client.Object)
		}
		var arg2 client.Patch
		if args[2] != nil {
			arg2 = args[2].(client.Patch)
		}
		var arg3 []client.SubResourcePatchOption
		var variadicArgs []client.SubResourcePatchOption
		if len(args) > 3 {
			variadicArgs = args[3].([]client.SubResourcePatchOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *SubResourceWriter_Patch_Call) Return(err error) *SubResourceWriter_Patch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubResourceWriter_Patch_Call) RunAndReturn(run func(ctx context.Context, obj client.Object, patch client.Patch, opts ...client.SubResourcePatchOption) error) *SubResourceWriter_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type SubResourceWriter
func (_mock *SubResourceWriter) Update(ctx context.Context, obj client.Object, opts ...client.SubResourceUpdateOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, obj, opts)
	} else {
		tmpRet = _mock.Called(ctx, obj)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.Object, ...client.SubResourceUpdateOption) error); ok {
		r0 = returnFunc(ctx, obj, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubResourceWriter_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type SubResourceWriter_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - obj client.Object
//   - opts ...client.SubResourceUpdateOption
func (_e *SubResourceWriter_Expecter) Update(ctx interface{}, obj interface{}, opts ...interface{}) *SubResourceWriter_Update_Call {
	return &SubResourceWriter_Update_Call{Call: _e.mock.On("Update",
		append([]interface{}{ctx, obj}, opts...)...)}
}

func (_c *SubResourceWriter_Update_Call) Run(run func(ctx context.Context, obj client.Object, opts ...client.SubResourceUpdateOption)) *SubResourceWriter_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.Object
		if args[1] != nil {
			arg1 = args[1].(client.Object)
		}
		var arg2 []client.SubResourceUpdateOption
		var variadicArgs []client.SubResourceUpdateOption
		if len(args) > 2 {
			variadicArgs = args[2].([]client.SubResourceUpdateOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *SubResourceWriter_Update_Call) Return(err error) *SubResourceWriter_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubResourceWriter_Update_Call) RunAndReturn(run func(ctx context.Context, obj client.Object, opts ...client.SubResourceUpdateOption) error) *SubResourceWriter_Update_Call {
	_c.Call.Return(run)
	return _c
}
