# Copyright The Platform Mesh Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Maximal permission policy RBAC for the marketplace.platform-mesh.io APIExport.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: marketplace-visibilitygrant-read
rules:
- apiGroups: ["marketplace.platform-mesh.io"]
  resources: ["visibilitygrants"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: visibilitygrant-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: marketplace-visibilitygrant-read
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: apis.kcp.io:binding:system:authenticated
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: marketplace-visibilitygrant-write
rules:
- apiGroups: ["marketplace.platform-mesh.io"]
  resources: ["visibilitygrants"]
  verbs: ["create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: visibilitygrant-write
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: marketplace-visibilitygrant-write
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  # TODO: this is deployment config? Is there a canonical admin group?
  # or just a convention we are following for now (e.g. local-setup etc)?
  name: apis.kcp.io:binding:pm:platform-admins
- apiGroup: rbac.authorization.k8s.io
  kind: User
  # local-setup KCP admin:
  name: apis.kcp.io:binding:kcp-admin
