//go:build !ignore_autogenerated

/*
Copyright The Platform Mesh Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIExportPolicy) DeepCopyInto(out *APIExportPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIExportPolicy.
func (in *APIExportPolicy) DeepCopy() *APIExportPolicy {
	if in == nil {
		return nil
	}
	out := new(APIExportPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIExportPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIExportPolicyList) DeepCopyInto(out *APIExportPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]APIExportPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIExportPolicyList.
func (in *APIExportPolicyList) DeepCopy() *APIExportPolicyList {
	if in == nil {
		return nil
	}
	out := new(APIExportPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIExportPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIExportPolicySpec) DeepCopyInto(out *APIExportPolicySpec) {
	*out = *in
	out.APIExportRef = in.APIExportRef
	if in.AllowPathExpressions != nil {
		in, out := &in.AllowPathExpressions, &out.AllowPathExpressions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIExportPolicySpec.
func (in *APIExportPolicySpec) DeepCopy() *APIExportPolicySpec {
	if in == nil {
		return nil
	}
	out := new(APIExportPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIExportPolicyStatus) DeepCopyInto(out *APIExportPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedAllowExpressions != nil {
		in, out := &in.ManagedAllowExpressions, &out.ManagedAllowExpressions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIExportPolicyStatus.
func (in *APIExportPolicyStatus) DeepCopy() *APIExportPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(APIExportPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIExportRef) DeepCopyInto(out *APIExportRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIExportRef.
func (in *APIExportRef) DeepCopy() *APIExportRef {
	if in == nil {
		return nil
	}
	out := new(APIExportRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Account) DeepCopyInto(out *Account) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Account.
func (in *Account) DeepCopy() *Account {
	if in == nil {
		return nil
	}
	out := new(Account)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Account) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountDefaulter) DeepCopyInto(out *AccountDefaulter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountDefaulter.
func (in *AccountDefaulter) DeepCopy() *AccountDefaulter {
	if in == nil {
		return nil
	}
	out := new(AccountDefaulter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountInfo) DeepCopyInto(out *AccountInfo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountInfo.
func (in *AccountInfo) DeepCopy() *AccountInfo {
	if in == nil {
		return nil
	}
	out := new(AccountInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountInfo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountInfoList) DeepCopyInto(out *AccountInfoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountInfoList.
func (in *AccountInfoList) DeepCopy() *AccountInfoList {
	if in == nil {
		return nil
	}
	out := new(AccountInfoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountInfoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountInfoSpec) DeepCopyInto(out *AccountInfoSpec) {
	*out = *in
	out.FGA = in.FGA
	out.Account = in.Account
	if in.ParentAccount != nil {
		in, out := &in.ParentAccount, &out.ParentAccount
		*out = new(AccountLocation)
		**out = **in
	}
	out.Organization = in.Organization
	out.ClusterInfo = in.ClusterInfo
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(OIDCInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountInfoSpec.
func (in *AccountInfoSpec) DeepCopy() *AccountInfoSpec {
	if in == nil {
		return nil
	}
	out := new(AccountInfoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountInfoStatus) DeepCopyInto(out *AccountInfoStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountInfoStatus.
func (in *AccountInfoStatus) DeepCopy() *AccountInfoStatus {
	if in == nil {
		return nil
	}
	out := new(AccountInfoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountList) DeepCopyInto(out *AccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Account, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountList.
func (in *AccountList) DeepCopy() *AccountList {
	if in == nil {
		return nil
	}
	out := new(AccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountLocation) DeepCopyInto(out *AccountLocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountLocation.
func (in *AccountLocation) DeepCopy() *AccountLocation {
	if in == nil {
		return nil
	}
	out := new(AccountLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountSpec) DeepCopyInto(out *AccountSpec) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Creator != nil {
		in, out := &in.Creator, &out.Creator
		*out = new(string)
		**out = **in
	}
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make([]Extension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountSpec.
func (in *AccountSpec) DeepCopy() *AccountSpec {
	if in == nil {
		return nil
	}
	out := new(AccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountStatus) DeepCopyInto(out *AccountStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.NextReconcileTime.DeepCopyInto(&out.NextReconcileTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountStatus.
func (in *AccountStatus) DeepCopy() *AccountStatus {
	if in == nil {
		return nil
	}
	out := new(AccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountValidator) DeepCopyInto(out *AccountValidator) {
	*out = *in
	if in.OrganizationNameDenyList != nil {
		in, out := &in.OrganizationNameDenyList, &out.OrganizationNameDenyList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AccountTypeAllowList != nil {
		in, out := &in.AccountTypeAllowList, &out.AccountTypeAllowList
		*out = make([]AccountType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountValidator.
func (in *AccountValidator) DeepCopy() *AccountValidator {
	if in == nil {
		return nil
	}
	out := new(AccountValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModel) DeepCopyInto(out *AuthorizationModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModel.
func (in *AuthorizationModel) DeepCopy() *AuthorizationModel {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthorizationModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModelList) DeepCopyInto(out *AuthorizationModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuthorizationModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModelList.
func (in *AuthorizationModelList) DeepCopy() *AuthorizationModelList {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthorizationModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModelSpec) DeepCopyInto(out *AuthorizationModelSpec) {
	*out = *in
	out.StoreRef = in.StoreRef
	if in.Tuples != nil {
		in, out := &in.Tuples, &out.Tuples
		*out = make([]Tuple, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModelSpec.
func (in *AuthorizationModelSpec) DeepCopy() *AuthorizationModelSpec {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModelStatus) DeepCopyInto(out *AuthorizationModelStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedTuples != nil {
		in, out := &in.ManagedTuples, &out.ManagedTuples
		*out = make([]Tuple, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModelStatus.
func (in *AuthorizationModelStatus) DeepCopy() *AuthorizationModelStatus {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientInfo) DeepCopyInto(out *ClientInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientInfo.
func (in *ClientInfo) DeepCopy() *ClientInfo {
	if in == nil {
		return nil
	}
	out := new(ClientInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterInfo) DeepCopyInto(out *ClusterInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterInfo.
func (in *ClusterInfo) DeepCopy() *ClusterInfo {
	if in == nil {
		return nil
	}
	out := new(ClusterInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentConfig) DeepCopyInto(out *ComponentConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentConfig.
func (in *ComponentConfig) DeepCopy() *ComponentConfig {
	if in == nil {
		return nil
	}
	out := new(ComponentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapReference) DeepCopyInto(out *ConfigMapReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapReference.
func (in *ConfigMapReference) DeepCopy() *ConfigMapReference {
	if in == nil {
		return nil
	}
	out := new(ConfigMapReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultAPIBindingConfiguration) DeepCopyInto(out *DefaultAPIBindingConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultAPIBindingConfiguration.
func (in *DefaultAPIBindingConfiguration) DeepCopy() *DefaultAPIBindingConfiguration {
	if in == nil {
		return nil
	}
	out := new(DefaultAPIBindingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailDomainRouting) DeepCopyInto(out *EmailDomainRouting) {
	*out = *in
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AutoRedirect != nil {
		in, out := &in.AutoRedirect, &out.AutoRedirect
		*out = new(bool)
		**out = **in
	}
	if in.HideUntilDomainMatch != nil {
		in, out := &in.HideUntilDomainMatch, &out.HideUntilDomainMatch
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailDomainRouting.
func (in *EmailDomainRouting) DeepCopy() *EmailDomainRouting {
	if in == nil {
		return nil
	}
	out := new(EmailDomainRouting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposureConfig) DeepCopyInto(out *ExposureConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposureConfig.
func (in *ExposureConfig) DeepCopy() *ExposureConfig {
	if in == nil {
		return nil
	}
	out := new(ExposureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Extension) DeepCopyInto(out *Extension) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.MetadataGoTemplate.DeepCopyInto(&out.MetadataGoTemplate)
	in.SpecGoTemplate.DeepCopyInto(&out.SpecGoTemplate)
	if in.ReadyConditionType != nil {
		in, out := &in.ReadyConditionType, &out.ReadyConditionType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Extension.
func (in *Extension) DeepCopy() *Extension {
	if in == nil {
		return nil
	}
	out := new(Extension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FGAInfo) DeepCopyInto(out *FGAInfo) {
	*out = *in
	out.Store = in.Store
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FGAInfo.
func (in *FGAInfo) DeepCopy() *FGAInfo {
	if in == nil {
		return nil
	}
	out := new(FGAInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureToggle) DeepCopyInto(out *FeatureToggle) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureToggle.
func (in *FeatureToggle) DeepCopy() *FeatureToggle {
	if in == nil {
		return nil
	}
	out := new(FeatureToggle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdPRegistration) DeepCopyInto(out *IdPRegistration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdPRegistration.
func (in *IdPRegistration) DeepCopy() *IdPRegistration {
	if in == nil {
		return nil
	}
	out := new(IdPRegistration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdPRegistration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdPRegistrationList) DeepCopyInto(out *IdPRegistrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IdPRegistration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdPRegistrationList.
func (in *IdPRegistrationList) DeepCopy() *IdPRegistrationList {
	if in == nil {
		return nil
	}
	out := new(IdPRegistrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdPRegistrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdPRegistrationOIDCConfig) DeepCopyInto(out *IdPRegistrationOIDCConfig) {
	*out = *in
	out.ClientSecretRef = in.ClientSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdPRegistrationOIDCConfig.
func (in *IdPRegistrationOIDCConfig) DeepCopy() *IdPRegistrationOIDCConfig {
	if in == nil {
		return nil
	}
	out := new(IdPRegistrationOIDCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdPRegistrationSecretRef) DeepCopyInto(out *IdPRegistrationSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdPRegistrationSecretRef.
func (in *IdPRegistrationSecretRef) DeepCopy() *IdPRegistrationSecretRef {
	if in == nil {
		return nil
	}
	out := new(IdPRegistrationSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdPRegistrationSpec) DeepCopyInto(out *IdPRegistrationSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.HideOnLoginPage != nil {
		in, out := &in.HideOnLoginPage, &out.HideOnLoginPage
		*out = new(bool)
		**out = **in
	}
	if in.EmailDomainRouting != nil {
		in, out := &in.EmailDomainRouting, &out.EmailDomainRouting
		*out = new(EmailDomainRouting)
		(*in).DeepCopyInto(*out)
	}
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(IdPRegistrationOIDCConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdPRegistrationSpec.
func (in *IdPRegistrationSpec) DeepCopy() *IdPRegistrationSpec {
	if in == nil {
		return nil
	}
	out := new(IdPRegistrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdPRegistrationStatus) DeepCopyInto(out *IdPRegistrationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LinkedEmailDomains != nil {
		in, out := &in.LinkedEmailDomains, &out.LinkedEmailDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdPRegistrationStatus.
func (in *IdPRegistrationStatus) DeepCopy() *IdPRegistrationStatus {
	if in == nil {
		return nil
	}
	out := new(IdPRegistrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProviderClientConfig) DeepCopyInto(out *IdentityProviderClientConfig) {
	*out = *in
	if in.RedirectURIs != nil {
		in, out := &in.RedirectURIs, &out.RedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostLogoutRedirectURIs != nil {
		in, out := &in.PostLogoutRedirectURIs, &out.PostLogoutRedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProviderClientConfig.
func (in *IdentityProviderClientConfig) DeepCopy() *IdentityProviderClientConfig {
	if in == nil {
		return nil
	}
	out := new(IdentityProviderClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProviderConfiguration) DeepCopyInto(out *IdentityProviderConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProviderConfiguration.
func (in *IdentityProviderConfiguration) DeepCopy() *IdentityProviderConfiguration {
	if in == nil {
		return nil
	}
	out := new(IdentityProviderConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdentityProviderConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProviderConfigurationList) DeepCopyInto(out *IdentityProviderConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IdentityProviderConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProviderConfigurationList.
func (in *IdentityProviderConfigurationList) DeepCopy() *IdentityProviderConfigurationList {
	if in == nil {
		return nil
	}
	out := new(IdentityProviderConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdentityProviderConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProviderConfigurationSpec) DeepCopyInto(out *IdentityProviderConfigurationSpec) {
	*out = *in
	if in.Clients != nil {
		in, out := &in.Clients, &out.Clients
		*out = make([]IdentityProviderClientConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProviderConfigurationSpec.
func (in *IdentityProviderConfigurationSpec) DeepCopy() *IdentityProviderConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(IdentityProviderConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProviderConfigurationStatus) DeepCopyInto(out *IdentityProviderConfigurationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedClients != nil {
		in, out := &in.ManagedClients, &out.ManagedClients
		*out = make(map[string]ManagedClient, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProviderConfigurationStatus.
func (in *IdentityProviderConfigurationStatus) DeepCopy() *IdentityProviderConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(IdentityProviderConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitializerConnection) DeepCopyInto(out *InitializerConnection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitializerConnection.
func (in *InitializerConnection) DeepCopy() *InitializerConnection {
	if in == nil {
		return nil
	}
	out := new(InitializerConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Invite) DeepCopyInto(out *Invite) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Invite.
func (in *Invite) DeepCopy() *Invite {
	if in == nil {
		return nil
	}
	out := new(Invite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Invite) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InviteList) DeepCopyInto(out *InviteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Invite, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InviteList.
func (in *InviteList) DeepCopy() *InviteList {
	if in == nil {
		return nil
	}
	out := new(InviteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InviteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InviteSpec) DeepCopyInto(out *InviteSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InviteSpec.
func (in *InviteSpec) DeepCopy() *InviteSpec {
	if in == nil {
		return nil
	}
	out := new(InviteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InviteStatus) DeepCopyInto(out *InviteStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InviteStatus.
func (in *InviteStatus) DeepCopy() *InviteStatus {
	if in == nil {
		return nil
	}
	out := new(InviteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KCPAPIVersionKindRef) DeepCopyInto(out *KCPAPIVersionKindRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KCPAPIVersionKindRef.
func (in *KCPAPIVersionKindRef) DeepCopy() *KCPAPIVersionKindRef {
	if in == nil {
		return nil
	}
	out := new(KCPAPIVersionKindRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kcp) DeepCopyInto(out *Kcp) {
	*out = *in
	if in.ProviderConnections != nil {
		in, out := &in.ProviderConnections, &out.ProviderConnections
		*out = make([]ProviderConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraProviderConnections != nil {
		in, out := &in.ExtraProviderConnections, &out.ExtraProviderConnections
		*out = make([]ProviderConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraDefaultAPIBindings != nil {
		in, out := &in.ExtraDefaultAPIBindings, &out.ExtraDefaultAPIBindings
		*out = make([]DefaultAPIBindingConfiguration, len(*in))
		copy(*out, *in)
	}
	if in.ExtraWorkspaces != nil {
		in, out := &in.ExtraWorkspaces, &out.ExtraWorkspaces
		*out = make([]WorkspaceDeclaration, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kcp.
func (in *Kcp) DeepCopy() *Kcp {
	if in == nil {
		return nil
	}
	out := new(Kcp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KcpWorkspace) DeepCopyInto(out *KcpWorkspace) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KcpWorkspace.
func (in *KcpWorkspace) DeepCopy() *KcpWorkspace {
	if in == nil {
		return nil
	}
	out := new(KcpWorkspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedClient) DeepCopyInto(out *ManagedClient) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedClient.
func (in *ManagedClient) DeepCopy() *ManagedClient {
	if in == nil {
		return nil
	}
	out := new(ManagedClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCMConfig) DeepCopyInto(out *OCMConfig) {
	*out = *in
	if in.Repo != nil {
		in, out := &in.Repo, &out.Repo
		*out = new(RepoConfig)
		**out = **in
	}
	if in.Component != nil {
		in, out := &in.Component, &out.Component
		*out = new(ComponentConfig)
		**out = **in
	}
	if in.ReferencePath != nil {
		in, out := &in.ReferencePath, &out.ReferencePath
		*out = make([]ReferencePathElement, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCMConfig.
func (in *OCMConfig) DeepCopy() *OCMConfig {
	if in == nil {
		return nil
	}
	out := new(OCMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCInfo) DeepCopyInto(out *OIDCInfo) {
	*out = *in
	if in.Clients != nil {
		in, out := &in.Clients, &out.Clients
		*out = make(map[string]ClientInfo, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCInfo.
func (in *OIDCInfo) DeepCopy() *OIDCInfo {
	if in == nil {
		return nil
	}
	out := new(OIDCInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCUpstreamConfig) DeepCopyInto(out *OIDCUpstreamConfig) {
	*out = *in
	if in.BackchannelLogout != nil {
		in, out := &in.BackchannelLogout, &out.BackchannelLogout
		*out = new(bool)
		**out = **in
	}
	out.ClientSecretRef = in.ClientSecretRef
	if in.AcceptsPromptNoneForwardFromClient != nil {
		in, out := &in.AcceptsPromptNoneForwardFromClient, &out.AcceptsPromptNoneForwardFromClient
		*out = new(bool)
		**out = **in
	}
	if in.RequiresShortStateParameter != nil {
		in, out := &in.RequiresShortStateParameter, &out.RequiresShortStateParameter
		*out = new(bool)
		**out = **in
	}
	if in.ValidateSignatures != nil {
		in, out := &in.ValidateSignatures, &out.ValidateSignatures
		*out = new(bool)
		**out = **in
	}
	if in.UseJWKSURL != nil {
		in, out := &in.UseJWKSURL, &out.UseJWKSURL
		*out = new(bool)
		**out = **in
	}
	if in.SupportsClientAssertions != nil {
		in, out := &in.SupportsClientAssertions, &out.SupportsClientAssertions
		*out = new(bool)
		**out = **in
	}
	if in.AllowsClientAssertionsReused != nil {
		in, out := &in.AllowsClientAssertionsReused, &out.AllowsClientAssertionsReused
		*out = new(bool)
		**out = **in
	}
	if in.AllowsClientIDAsAudienceForAssertions != nil {
		in, out := &in.AllowsClientIDAsAudienceForAssertions, &out.AllowsClientIDAsAudienceForAssertions
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCUpstreamConfig.
func (in *OIDCUpstreamConfig) DeepCopy() *OIDCUpstreamConfig {
	if in == nil {
		return nil
	}
	out := new(OIDCUpstreamConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformMesh) DeepCopyInto(out *PlatformMesh) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformMesh.
func (in *PlatformMesh) DeepCopy() *PlatformMesh {
	if in == nil {
		return nil
	}
	out := new(PlatformMesh)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformMesh) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformMeshList) DeepCopyInto(out *PlatformMeshList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlatformMesh, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformMeshList.
func (in *PlatformMeshList) DeepCopy() *PlatformMeshList {
	if in == nil {
		return nil
	}
	out := new(PlatformMeshList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformMeshList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformMeshSpec) DeepCopyInto(out *PlatformMeshSpec) {
	*out = *in
	if in.Exposure != nil {
		in, out := &in.Exposure, &out.Exposure
		*out = new(ExposureConfig)
		**out = **in
	}
	in.Kcp.DeepCopyInto(&out.Kcp)
	in.Values.DeepCopyInto(&out.Values)
	if in.OCM != nil {
		in, out := &in.OCM, &out.OCM
		*out = new(OCMConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.FeatureToggles != nil {
		in, out := &in.FeatureToggles, &out.FeatureToggles
		*out = make([]FeatureToggle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.InfraValues.DeepCopyInto(&out.InfraValues)
	if in.Wait != nil {
		in, out := &in.Wait, &out.Wait
		*out = new(WaitConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ProfileConfigMap != nil {
		in, out := &in.ProfileConfigMap, &out.ProfileConfigMap
		*out = new(ConfigMapReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformMeshSpec.
func (in *PlatformMeshSpec) DeepCopy() *PlatformMeshSpec {
	if in == nil {
		return nil
	}
	out := new(PlatformMeshSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformMeshStatus) DeepCopyInto(out *PlatformMeshStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.NextReconcileTime.DeepCopyInto(&out.NextReconcileTime)
	if in.KcpWorkspaces != nil {
		in, out := &in.KcpWorkspaces, &out.KcpWorkspaces
		*out = make([]KcpWorkspace, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformMeshStatus.
func (in *PlatformMeshStatus) DeepCopy() *PlatformMeshStatus {
	if in == nil {
		return nil
	}
	out := new(PlatformMeshStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConnection) DeepCopyInto(out *ProviderConnection) {
	*out = *in
	if in.EndpointSliceName != nil {
		in, out := &in.EndpointSliceName, &out.EndpointSliceName
		*out = new(string)
		**out = **in
	}
	if in.APIExportNames != nil {
		in, out := &in.APIExportNames, &out.APIExportNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RawPath != nil {
		in, out := &in.RawPath, &out.RawPath
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.AdminAuth != nil {
		in, out := &in.AdminAuth, &out.AdminAuth
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConnection.
func (in *ProviderConnection) DeepCopy() *ProviderConnection {
	if in == nil {
		return nil
	}
	out := new(ProviderConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReferencePathElement) DeepCopyInto(out *ReferencePathElement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReferencePathElement.
func (in *ReferencePathElement) DeepCopy() *ReferencePathElement {
	if in == nil {
		return nil
	}
	out := new(ReferencePathElement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoConfig) DeepCopyInto(out *RepoConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoConfig.
func (in *RepoConfig) DeepCopy() *RepoConfig {
	if in == nil {
		return nil
	}
	out := new(RepoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceType) DeepCopyInto(out *ResourceType) {
	*out = *in
	out.GroupVersionKind = in.GroupVersionKind
	in.LabelSelector.DeepCopyInto(&out.LabelSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceType.
func (in *ResourceType) DeepCopy() *ResourceType {
	if in == nil {
		return nil
	}
	out := new(ResourceType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Store) DeepCopyInto(out *Store) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Store.
func (in *Store) DeepCopy() *Store {
	if in == nil {
		return nil
	}
	out := new(Store)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Store) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreInfo) DeepCopyInto(out *StoreInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreInfo.
func (in *StoreInfo) DeepCopy() *StoreInfo {
	if in == nil {
		return nil
	}
	out := new(StoreInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreList) DeepCopyInto(out *StoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Store, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreList.
func (in *StoreList) DeepCopy() *StoreList {
	if in == nil {
		return nil
	}
	out := new(StoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreSpec) DeepCopyInto(out *StoreSpec) {
	*out = *in
	if in.Tuples != nil {
		in, out := &in.Tuples, &out.Tuples
		*out = make([]Tuple, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreSpec.
func (in *StoreSpec) DeepCopy() *StoreSpec {
	if in == nil {
		return nil
	}
	out := new(StoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreStatus) DeepCopyInto(out *StoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedTuples != nil {
		in, out := &in.ManagedTuples, &out.ManagedTuples
		*out = make([]Tuple, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreStatus.
func (in *StoreStatus) DeepCopy() *StoreStatus {
	if in == nil {
		return nil
	}
	out := new(StoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tuple) DeepCopyInto(out *Tuple) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tuple.
func (in *Tuple) DeepCopy() *Tuple {
	if in == nil {
		return nil
	}
	out := new(Tuple)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamIdentityProvider) DeepCopyInto(out *UpstreamIdentityProvider) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.HideOnLoginPage != nil {
		in, out := &in.HideOnLoginPage, &out.HideOnLoginPage
		*out = new(bool)
		**out = **in
	}
	if in.EmailDomainRouting != nil {
		in, out := &in.EmailDomainRouting, &out.EmailDomainRouting
		*out = new(EmailDomainRouting)
		(*in).DeepCopyInto(*out)
	}
	if in.AccountLinkingOnly != nil {
		in, out := &in.AccountLinkingOnly, &out.AccountLinkingOnly
		*out = new(bool)
		**out = **in
	}
	if in.StoreTokens != nil {
		in, out := &in.StoreTokens, &out.StoreTokens
		*out = new(bool)
		**out = **in
	}
	if in.StoredTokensReadable != nil {
		in, out := &in.StoredTokensReadable, &out.StoredTokensReadable
		*out = new(bool)
		**out = **in
	}
	if in.TrustEmail != nil {
		in, out := &in.TrustEmail, &out.TrustEmail
		*out = new(bool)
		**out = **in
	}
	if in.GUIOrder != nil {
		in, out := &in.GUIOrder, &out.GUIOrder
		*out = new(int)
		**out = **in
	}
	if in.VerifyEssentialClaim != nil {
		in, out := &in.VerifyEssentialClaim, &out.VerifyEssentialClaim
		*out = new(bool)
		**out = **in
	}
	if in.CaseSensitiveUsername != nil {
		in, out := &in.CaseSensitiveUsername, &out.CaseSensitiveUsername
		*out = new(bool)
		**out = **in
	}
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(OIDCUpstreamConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamIdentityProvider.
func (in *UpstreamIdentityProvider) DeepCopy() *UpstreamIdentityProvider {
	if in == nil {
		return nil
	}
	out := new(UpstreamIdentityProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitConfig) DeepCopyInto(out *WaitConfig) {
	*out = *in
	if in.ResourceTypes != nil {
		in, out := &in.ResourceTypes, &out.ResourceTypes
		*out = make([]ResourceType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitConfig.
func (in *WaitConfig) DeepCopy() *WaitConfig {
	if in == nil {
		return nil
	}
	out := new(WaitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookConfiguration) DeepCopyInto(out *WebhookConfiguration) {
	*out = *in
	out.SecretRef = in.SecretRef
	out.WebhookRef = in.WebhookRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookConfiguration.
func (in *WebhookConfiguration) DeepCopy() *WebhookConfiguration {
	if in == nil {
		return nil
	}
	out := new(WebhookConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceDeclaration) DeepCopyInto(out *WorkspaceDeclaration) {
	*out = *in
	out.Type = in.Type
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceDeclaration.
func (in *WorkspaceDeclaration) DeepCopy() *WorkspaceDeclaration {
	if in == nil {
		return nil
	}
	out := new(WorkspaceDeclaration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceStoreRef) DeepCopyInto(out *WorkspaceStoreRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceStoreRef.
func (in *WorkspaceStoreRef) DeepCopy() *WorkspaceStoreRef {
	if in == nil {
		return nil
	}
	out := new(WorkspaceStoreRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceTypeReference) DeepCopyInto(out *WorkspaceTypeReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceTypeReference.
func (in *WorkspaceTypeReference) DeepCopy() *WorkspaceTypeReference {
	if in == nil {
		return nil
	}
	out := new(WorkspaceTypeReference)
	in.DeepCopyInto(out)
	return out
}
