//go:build !ignore_autogenerated

/*
Copyright The Platform Mesh Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apisv1alpha1 "github.com/kcp-dev/sdk/apis/apis/v1alpha1"
	"github.com/kcp-dev/sdk/apis/apis/v1alpha2"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LegacyAPIExport) DeepCopyInto(out *LegacyAPIExport) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LegacyAPIExport.
func (in *LegacyAPIExport) DeepCopy() *LegacyAPIExport {
	if in == nil {
		return nil
	}
	out := new(LegacyAPIExport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LegacyAPIExportSpec) DeepCopyInto(out *LegacyAPIExportSpec) {
	*out = *in
	if in.LatestResourceSchemas != nil {
		in, out := &in.LatestResourceSchemas, &out.LatestResourceSchemas
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(apisv1alpha1.Identity)
		(*in).DeepCopyInto(*out)
	}
	if in.MaximalPermissionPolicy != nil {
		in, out := &in.MaximalPermissionPolicy, &out.MaximalPermissionPolicy
		*out = new(apisv1alpha1.MaximalPermissionPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.PermissionClaims != nil {
		in, out := &in.PermissionClaims, &out.PermissionClaims
		*out = make([]LegacyPermissionClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LegacyAPIExportSpec.
func (in *LegacyAPIExportSpec) DeepCopy() *LegacyAPIExportSpec {
	if in == nil {
		return nil
	}
	out := new(LegacyAPIExportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LegacyPermissionClaim) DeepCopyInto(out *LegacyPermissionClaim) {
	*out = *in
	if in.ResourceSelector != nil {
		in, out := &in.ResourceSelector, &out.ResourceSelector
		*out = make([]apisv1alpha1.ResourceSelector, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LegacyPermissionClaim.
func (in *LegacyPermissionClaim) DeepCopy() *LegacyPermissionClaim {
	if in == nil {
		return nil
	}
	out := new(LegacyPermissionClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarketplaceEntry) DeepCopyInto(out *MarketplaceEntry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarketplaceEntry.
func (in *MarketplaceEntry) DeepCopy() *MarketplaceEntry {
	if in == nil {
		return nil
	}
	out := new(MarketplaceEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MarketplaceEntry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarketplaceEntryList) DeepCopyInto(out *MarketplaceEntryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MarketplaceEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarketplaceEntryList.
func (in *MarketplaceEntryList) DeepCopy() *MarketplaceEntryList {
	if in == nil {
		return nil
	}
	out := new(MarketplaceEntryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MarketplaceEntryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarketplaceEntrySpec) DeepCopyInto(out *MarketplaceEntrySpec) {
	*out = *in
	in.ProviderMetadata.DeepCopyInto(&out.ProviderMetadata)
	in.APIExport.DeepCopyInto(&out.APIExport)
	if in.APIExportPermissionClaims != nil {
		in, out := &in.APIExportPermissionClaims, &out.APIExportPermissionClaims
		*out = make([]v1alpha2.PermissionClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarketplaceEntrySpec.
func (in *MarketplaceEntrySpec) DeepCopy() *MarketplaceEntrySpec {
	if in == nil {
		return nil
	}
	out := new(MarketplaceEntrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarketplaceEntryStatus) DeepCopyInto(out *MarketplaceEntryStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarketplaceEntryStatus.
func (in *MarketplaceEntryStatus) DeepCopy() *MarketplaceEntryStatus {
	if in == nil {
		return nil
	}
	out := new(MarketplaceEntryStatus)
	in.DeepCopyInto(out)
	return out
}
