apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: providers.platform-mesh.io
spec:
  resources:
  - group: providers.platform-mesh.io
    name: providerpermissions
    schema: v260703-0c370717.providerpermissions.providers.platform-mesh.io
    storage:
      crd: {}
status: {}
